cpufreq: error during build and remove unused vars
drivers/cpufreq/cpufreq_governor.c: In function '__gov_queue_work':
drivers/cpufreq/cpufreq_governor.c:168:2: error: implicit declaration of function 'mod_delayed_work_on' [-Werror=implicit-function-declaration]
  mod_delayed_work_on(cpu, system_wq, &cdbs->work, delay);
  ^
drivers/cpufreq/cpufreq_governor.c: In function 'cpufreq_governor_dbs':
drivers/cpufreq/cpufreq_governor.c:386:4: error: implicit declaration of function 'INIT_DEFERRABLE_WORK' [-Werror=implicit-function-declaration]
    INIT_DEFERRABLE_WORK(&j_cdbs->work,

Change-Id: I562cacb66ed8c356805676da840f2fedea8f0755
Signed-off-by: HASH <hash.xda@gmail.com>